name: 🐛 Отчет об ошибке
description: Сообщить о технической проблеме или баге в WarpBypass
title: '[BUG] '
labels: ['bug', 'needs triage']

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ⚠️ Чеклист
      description: Перед созданием нового Issue, удостоверьтесь, что выполнили следующие пункты:
      options:
        - label: Я внимательно прочитал [README](https://github.com/rydve/WarpBypass/blob/main/README.md)
        - label: Я использую последнюю версию `WarpBypass.bat` из официального репозитория
        - label: Я запускаю скрипт от имени Администратора

  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Максимально подробно опишите проблему, с которой вы столкнулись.
      placeholder: При запуске профиля alt12 консоль выдает ошибку...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Версия WarpBypass
      description: Укажите версию утилиты (указана в главном меню)
      placeholder: v4.4
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Версия Windows
      description: Укажите вашу версию и сборку Windows (например, Windows 11 23H2)
      placeholder: Windows 11
    validations:
      required: true

  - type: dropdown
    id: dns_fix
    attributes:
      label: Включен ли "Временный DNS Фикс" в настройках?
      options:
        - "Да"
        - "Нет"
        - "Не знаю"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Логи / Текст ошибки
      description: Скопируйте текст ошибки из консоли сюда (по желанию)
